### ISSUE TITLE
delete.pronouns has no effect

### ISSUE THREAD

**Issue by snaut** [computationalstylistics/stylo#12]
Despite checking delete pronouns in the gui the `table.with.all.freqs` as well as the `features.actually.used` contain words like  "the", "a", "he". Entering `delete.pronouns = TRUE` in `stylo_config.txt` also has no effect. 

Maybe this is due to a missing word list, in this case a warning should be shown in the gui or the commandline when running non-interactively.

[session_info.txt](https://github.com/computationalstylistics/stylo/files/1593209/session_info.txt)
[r_version.txt](https://github.com/computationalstylistics/stylo/files/1593210/r_version.txt)
[stylo_config.txt](https://github.com/computationalstylistics/stylo/files/1593213/stylo_config.txt)

**Comment by computationalstylistics** [comment]
Thanks for pointing that out. However, its is more about a confusing documentation than an actual issue in the code. Deleting pronouns makes sure that the words "he", "she", "herself" etc. are neutralized. To delete more words, you should indicate them via the `stop.words` parameter:

```
library(stylo)
data(lee)
my.stopword.list = c("the", "of", "and")
a = stylo(lee, stop.words = my.stopword.list)
a$features.actually.used
```
to see which words are included into the list of pronouns, type:

```
stylo.pronouns()
help(stylo.pronouns)
```

**Comment by snaut** [comment]
Sorry for miss reporting, thank you for your reply.
