### ISSUE TITLE
Not all parameters retrieved from stylo_config.txt

### ISSUE THREAD

**Issue by christofs** [computationalstylistics/stylo#13]
When calling stylo() several times, parameters are supposed to be saved to the file "stylo_config.txt". However, for some reason, the parameter "delta.distance" will not be saved and then default to "Classic Delta" on the next run. At least, this is what I observe on Ubuntu 18.04, R 3.4.4 and stylo 0.6.6. It would be more convenient if the Delta Variant was also saved and retrieved.

**Comment by computationalstylistics** [comment]
Thanks, Christof, for pointing this out! Will have a look. First versions of 'stylo' supported Delta only, and therefore there was no need to care about the distance metrics.

**Comment by computationalstylistics** [comment]
Solved. On GitHub now.
