### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by sblss** [computationalstylistics/stylo#19]
Hello,

I have some questions for an article about stylo that is mainly addressed to beginners of DH, but also collects information for more experienced users of digital text tools. Sorry, I am not sure if this is the right place to ask, but I did not find a better contact to use.
So the first question is: What is the best way for a user to contact you if he has problems using stylo?
Another part of the article will be which types of file you put in and get out as results or as materials to continue working. So you put in texts in TXT, HTML and TEI-XMLand get out visualizations in PDF, JPG, PNG and SVG plus runreports in TXT. Is there something important missing, both for beginners and more advanced users?
About privacy: I was told that nothing is saved except the final table of word frequencies. Is this table also saved, if I use stylo offline? And is the data used to improve the tool or for what reason? How long is the data stored and can I ask for it to be deleted or not collected?

Thank you very much!

**Comment by Frenzie** [comment]
> if I use stylo offline?

is there any other way? :-)

**Comment by sblss** [comment]
I was not sure since I was told that this table is saved. How is it transfered if the program never goes online?

**Comment by sblss** [comment]
I asked some previous questions by mail, among other things about privacy: Does the package store any personal information. The answer was it stores nothing but the table. If it was only saved on my computer that would not be a privacy issue, but since it was mentioned in this context, that can't be all and I suppose it has to be transferred somehow?
