### ISSUE TITLE
stylo main function performance problem

### ISSUE THREAD

**Issue by adunmore** [computationalstylistics/stylo#32]
`stylo()`, constructs `wordlist.of.loaded.corpus` using variable reassignment. Finding another way to generate the corpus wordlist would speed the execution of `stylo()` significantly, especially on large corpuses.

**Comment by computationalstylistics** [comment]
Hi there! Thanks a lot for raising all the issues recently – all suggestions are more than welcome! I'll dig into it in a couple of days time.

**Comment by adunmore** [comment]
@computationalstylistics Of course! I'm currently working on a project using Stylo with a pretty big corpus, and I'll continue to submit improvements as I work to make it a little faster/easier for us to use 👍
