### ISSUE TITLE
error with pca.visual.flavour="symbols"

### ISSUE THREAD

**Issue by jmclawson** [computationalstylistics/stylo#43]
When setting `pca.visual.flavour="symbols"`, the following error appears in the console:

> Error in fun(key = base::quote(list(columns = 2, text = list(NULL), points = list( : 
  first component of text must be vector of labels

Upon investigating, this error seems to have been introduced with R 4.0, which changed an important default for `data.frame()` to `stringsAsFactors = FALSE`. (See explanation [here](https://developer.r-project.org/Blog/public/2020/02/16/stringsasfactors/index.html).) 

It's possible this changed default will result in errors in other parts of the codebase, too, but this specific scenario is the only problem I've seen so far. I have a change ready to fix this specific error, coming up in a jiffy.

**Comment by computationalstylistics** [comment]
Sure, it makes a lot of sense! I hope it works now
