### ISSUE TITLE
Lemmatization in stylo?

### ISSUE THREAD

**Issue by nightowl15** [computationalstylistics/stylo#59]
Hi, I would like to know if Stylo does lemmatization on the text before tokenizing the words. I am a data science student, and I am familiar with using RStudio. I am working on analyzing Russian text, but I want to know if the Stylo package uses lemmatization algorithms. If it does, is there a way to access the function inside of the stylo package? Also, I read that the Elder's Delta is recommended when analyzing inflected languages like Russian. How comparable is lemmatization against the Elder's Delta?

**Comment by christofs** [comment]
As far as I know, it does not. If you need to use lemmatized words as features, you will need to do this outside of stylo beforehand. 

I don't think the choice between word forms and lemmas on the one hand, and between, say, Classic Delta, Eder's Delta or Cosine Delta, can be directly compared. 

My recommendation would be to test stylo on a corpus in Russian where you know all the authors, in a first step, and in this way find out what parameters work well with Russian.

**Comment by nightowl15** [comment]
Reading the documentation that the stylo package provides indicates that there is not a lemmatization process when running a stylo analysis.
